//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Spot.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_SPOTTYPE                    129
#define IDD_PREFIXDLG                   131
#define IDR_GESTTYPE                    132
#define IDD_ABOUTHMM                    135
#define IDC_PREFIX                      1000
#define IDC_NUMBER                      1001
#define IDM_START_GRAB                  32771
#define IDM_FINISH_GRAB                 32772
#define IDM_DUMP_FRAME                  32773
#define ID_DISP_CONTINUOUS              32774
#define ID_DISP_BY_FRAME                32775
#define ID_AUTOSAVE                     32776
#define IDM_DISPLAY_FRAME               32777
#define ID_SHOW_GRAY                    32778
#define ID_GET_Y                        32779
#define ID_GET_I                        32780
#define IDM_TRACK_HAND                  32781
#define ID_HMM_TRAIN                    32782
#define ID_HMM_TEST                     32783
#define ID_HMM_ASCII                    32784
#define IDM_START_CAPTURE               32785
#define IDM_CLEAR_DISPLAY               32786
#define IDM_EDIT_STROKE                 32787
#define IDM_EDIT_NEXT_STROKE            32788
#define IDM_EDIT_SAVE_STROKE            32789
#define IDM_VECTOR_QUANTIZE             32790
#define IDM_LEARN_VQ                    32791
#define IDM_EDIT_PREV_STROKE            32792
#define IDM_MAKE_NORMAL_VQ              32793
#define IDM_ONLINE_TEST                 32794
#define IDM_RESAVE_ALL                  32795
#define IDM_DO_ALL                      32796
#define IDM_MAKE_LIST_FILE              32797
#define IDM_NEXT10_STROKE               32798
#define IDM_RECOG_HAND_GESTURE          32799
#define IDM_PREV10_STROKE               32800
#define IDM_START_RECOGNIZE             32801
#define IDM_LOAD_THRESHOLD_HMM          32802
#define IDM_MAKE_THRESHOLD_MODEL        32803
#define IDM_TRAIN_THRESHOLD             32804
#define IDM_INIT_MODEL                  32805
#define IDM_MODEL_LAST                  32810
#define IDM_MODEL_FIRST                 32811
#define IDM_MODEL_NEXT                  32812
#define IDM_MODEL_PREV                  32813
#define IDM_MODEL_QUIT                  32814
#define IDM_MODEL_BYE                   32815
#define IDM_MODEL_CIRCLE                32816
#define IDM_MODEL_TRIANGLE              32817
#define IDM_MODEL_SAW                   32818
#define IDM_MODEL_ALPHA                 32819
#define IDM_MODEL_THRESHOLD             32820
#define IDM_TEST_LAST                   32830
#define IDM_TEST_FIRST                  32831
#define IDM_TEST_NEXT                   32832
#define IDM_TEST_PREV                   32833
#define IDM_TEST_QUIT                   32834
#define IDM_TEST_BYE                    32835
#define IDM_TEST_CIRCLE                 32836
#define IDM_TEST_TRIANGLE               32837
#define IDM_TEST_SAW                    32838
#define IDM_TEST_ALPHA                  32839
#define IDM_TEST_THRESHOLD              32840
#define IDM_SHOW_RECOGNITION            32850
#define IDM_SINGLE_TRANS                32851
#define IDM_TEST_TRAIN_DATA             32852
#define IDM_EDIT_CHANGE_STROKE          32853
#define IDM_SHOW_MATCH                  32854
#define IDM_UNITE_MODEL                 32855
#define IDM_TEST_UNITED                 32856
#define IDM_MAKE_METAFILE               32857
#define IDM_IMMEDIATE_RECOG             32858
#define IDM_EDIT_FRAME                  32859
#define IDM_SET_LASTDATA                32860
#define IDM_SET_FIRSTDATA               32861
#define IDM_SET_NEXTDATA                32862
#define IDM_SET_PREVDATA                32863
#define IDM_SET_QUITDATA                32864
#define IDM_SET_BYEDATA                 32865
#define IDM_SET_CIRCLEDATA              32866
#define IDM_SET_TRIANGLEDATA            32867
#define IDM_SET_SAWDATA                 32868
#define IDM_SET_ALPHADATA               32869
#define IDM_SET_THRESHOLDDATA           32870
#define IDM_SET_TESTDATA                32871
#define IDM_GEN_LASTDATA                32880
#define IDM_GEN_FIRSTDATA               32881
#define IDM_GEN_NEXTDATA                32882
#define IDM_GEN_PREVDATA                32883
#define IDM_GEN_QUITDATA                32884
#define IDM_GEN_BYEDATA                 32885
#define IDM_GEN_CIRCLEDATA              32886
#define IDM_GEN_TRIANGLEDATA            32887
#define IDM_GEN_SAWDATA                 32888
#define IDM_GEN_ALPHADATA               32889
#define IDM_GEN_THRESHOLDDATA           32890
#define IDM_GEN_TESTDATA                32891
#define IDM_NEXT_DUMP_FILE              32900
#define IDM_PREV_DUMP_FILE              32901
#define IDM_NEXT10_DUMP_FILE            32902
#define IDM_PREV10_DUMP_FILE            32903
#define IDM_GENERATE_ALL_FEATURE        32904
#define IDM_SAVE_SNAP_FRAME             32905
#define IDM_LABELLING                   32906
#define IDM_COUNT_LABEL                 32907
#define IDM_RECOG_TEST_DATA             32908
#define IDM_GEN_TEST_RESULT             32909
#define IDM_GEN_CUR_FEATURE             32910
#define IDM_CHECK_FRAME_RATE            32911
#define IDM_REDUCEDTHRESHOLD			32930

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         32798
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
